/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Dictionary.ui;

import com.sun.management.VMOption;
import java.io.*;
import com.sun.speech.freetts.*;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author MINH QUY
 */
public class Dictionary extends javax.swing.JFrame {

    /**
     * Creates new form Dictionary
     */
    
    DefaultListModel defaultListModel = new DefaultListModel();
    //VoiceManager vm;
    //Voice v;
    
    private ArrayList getInputs() {
        ArrayList inputs = new ArrayList();
        inputs.add("intelligent");
        inputs.add("shine");
        inputs.add("love");
        inputs.add("address");
        inputs.add("piss");
        inputs.add("important");
        inputs.add("colection");
        inputs.add("caculus");
        inputs.add("avalible");
        inputs.add("pizza");
        inputs.add("pixels");
        inputs.add("spring");
        inputs.add("component");
        inputs.add("cost");
        inputs.add("manager");
        inputs.add("junior");
        inputs.add("senior");
        inputs.add("lead");
        inputs.add("president");
        inputs.add("hello");
        return inputs;
    }
    
    public Dictionary() {
        initComponents();
        this.bindData();
        Search.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            } 
        });
        
    }

    
    
    private void bindData() {
        getInputs().stream().forEach((input) -> {
            defaultListModel.addElement(input);
        });
        FilterWord.setModel(defaultListModel);
        FilterWord.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    private void SearchFilter(String WordInputs) {
        DefaultListModel filteredItem = new DefaultListModel();
        ArrayList inputs = getInputs();
        inputs.stream().forEach((input) -> {
            String inputname = input.toString().toLowerCase();
            if(inputname.contains(WordInputs.toLowerCase())) {
                filteredItem.addElement(input);
            } 
        });
        defaultListModel = filteredItem;
        FilterWord.setModel(defaultListModel);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Search = new javax.swing.JButton();
        WordInput = new javax.swing.JTextField();
        Output = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FilterWord = new javax.swing.JList<>();
        Speaker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Search.setBackground(new java.awt.Color(0, 255, 0));
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        WordInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WordInputKeyReleased(evt);
            }
        });

        Output.setBackground(new java.awt.Color(255, 255, 255));
        Output.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Output.setOpaque(true);

        FilterWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FilterWordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FilterWord);

        Speaker.setText("Speaker");
        Speaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeakerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(WordInput, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(Speaker))
                    .addComponent(Output, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Speaker))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        
        String input = WordInput.getText();
         Output.setText(input);
    }//GEN-LAST:event_SearchActionPerformed

    private void FilterWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FilterWordMouseClicked
        JOptionPane.showMessageDialog(rootPane, FilterWord.getSelectedValue() , "Input choice",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_FilterWordMouseClicked

    private void WordInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WordInputKeyReleased
        // TODO add your handling code here:
        SearchFilter(WordInput.getText());
    }//GEN-LAST:event_WordInputKeyReleased

    private static final String VOICENAME = "kevin16";
    private void SpeakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeakerActionPerformed
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");
        
        voice.allocate();
        voice.speak(WordInput.getText().trim());
    }//GEN-LAST:event_SpeakerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> FilterWord;
    private javax.swing.JLabel Output;
    private javax.swing.JButton Search;
    private javax.swing.JButton Speaker;
    private javax.swing.JTextField WordInput;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
